# Generated by Django 5.0.2 on 2025-05-28 19:01

import examples.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('biz', '0003_businessexample_updated_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='businessexample',
            name='image',
            field=examples.fields.CompressedImageField(blank=True, null=True, upload_to='business_examples/'),
        ),
    ]
