# Generated by Django 5.0.2 on 2025-05-29 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biz', '0004_alter_businessexample_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='businessexample',
            name='types',
            field=models.ManyToManyField(related_name='examples', to='biz.businesstype'),
        ),
    ]
