# Generated by Django 5.0.2 on 2025-05-28 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EcommerceType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'E-commerce Type',
                'verbose_name_plural': 'E-commerce Types',
            },
        ),
        migrations.CreateModel(
            name='EcommerceDemo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('image', models.ImageField(upload_to='ecommerce_demos/')),
                ('link', models.URLField()),
                ('category', models.CharField(choices=[('single', 'Single Vendor'), ('multi', 'Multivendor')], max_length=10)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('types', models.ManyToManyField(related_name='demos', to='ecom.ecommercetype')),
            ],
            options={
                'verbose_name': 'E-commerce Demo',
                'verbose_name_plural': 'E-commerce Demos',
            },
        ),
    ]
