# Generated by Django 5.0.2 on 2025-05-28 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecom', '0002_ecommercedemo_tags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ecommercedemo',
            name='category',
            field=models.CharField(blank=True, choices=[('fashion', 'Fashion & Apparel'), ('electronics', 'Electronics'), ('food', 'Food & Beverage'), ('health', 'Health & Beauty'), ('home', 'Home & Garden'), ('sports', 'Sports & Outdoors'), ('other', 'Other')], max_length=20),
        ),
    ]
