# Generated by Django 5.0.2 on 2025-05-28 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecom', '0003_alter_ecommercedemo_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ecommercedemo',
            name='category',
            field=models.CharField(blank=True, choices=[('fashion_single', 'Fashion & Apparel - Single Vendor'), ('fashion_multi', 'Fashion & Apparel - Multivendor'), ('electronics_single', 'Electronics - Single Vendor'), ('electronics_multi', 'Electronics - Multivendor'), ('food_single', 'Food & Beverage - Single Vendor'), ('food_multi', 'Food & Beverage - Multivendor'), ('health_single', 'Health & Beauty - Single Vendor'), ('health_multi', 'Health & Beauty - Multivendor'), ('home_single', 'Home & Garden - Single Vendor'), ('home_multi', 'Home & Garden - Multivendor'), ('sports_single', 'Sports & Outdoors - Single Vendor'), ('sports_multi', 'Sports & Outdoors - Multivendor'), ('other_single', 'Other - Single Vendor'), ('other_multi', 'Other - Multivendor')], max_length=30),
        ),
    ]
