# Generated by Django 5.0.2 on 2025-05-28 18:20

import taggit.managers
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecom', '0005_alter_ecommercedemo_category'),
        ('taggit', '0006_rename_taggeditem_content_type_object_id_taggit_tagg_content_8fc721_idx'),
    ]

    operations = [
        migrations.AddField(
            model_name='ecommercedemo',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='ecommercedemo',
            name='category',
            field=models.CharField(choices=[('fashion', 'Fashion'), ('electronics', 'Electronics'), ('food', 'Food & Beverage'), ('health', 'Health & Beauty'), ('home', 'Home & Garden'), ('sports', 'Sports & Outdoors'), ('toys', 'Toys & Games'), ('other', 'Other')], default='other', max_length=20),
        ),
        migrations.AlterField(
            model_name='ecommercedemo',
            name='description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='ecommercedemo',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='ecommerce_demos/'),
        ),
        migrations.AlterField(
            model_name='ecommercedemo',
            name='tags',
            field=taggit.managers.TaggableManager(help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags'),
        ),
        migrations.AlterField(
            model_name='ecommercedemo',
            name='types',
            field=models.ManyToManyField(to='ecom.ecommercetype'),
        ),
    ]
