# Generated by Django 5.0.2 on 2025-05-28 19:01

import examples.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecom', '0006_ecommercedemo_updated_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ecommercedemo',
            name='category',
            field=models.CharField(choices=[('fashion', 'Fashion & Apparel'), ('electronics', 'Electronics & Gadgets'), ('home', 'Home & Furniture'), ('beauty', 'Beauty & Personal Care'), ('food', 'Food & Grocery'), ('sports', 'Sports & Fitness'), ('books', 'Books & Media'), ('toys', 'Toys & Games'), ('health', 'Health & Wellness'), ('other', 'Other')], default='other', max_length=20),
        ),
        migrations.AlterField(
            model_name='ecommercedemo',
            name='image',
            field=examples.fields.CompressedImageField(blank=True, null=True, upload_to='ecommerce_demos/'),
        ),
    ]
