# Generated by Django 5.0.2 on 2025-05-28 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecom', '0007_alter_ecommercedemo_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ecommercedemo',
            name='category',
            field=models.CharField(choices=[('single', 'Single Vendor'), ('multi', 'Multi Vendor')], default='single', max_length=20),
        ),
    ]
