# Generated by Django 5.0.2 on 2025-05-29 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecom', '0008_alter_ecommercedemo_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ecommercedemo',
            name='types',
            field=models.ManyToManyField(related_name='demos', to='ecom.ecommercetype'),
        ),
    ]
