# Generated by Django 5.0.2 on 2025-05-28 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WebAppType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Web App Type',
                'verbose_name_plural': 'Web App Types',
            },
        ),
        migrations.CreateModel(
            name='WebAppDemo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('image', models.ImageField(upload_to='webapp_demos/')),
                ('link', models.URLField()),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('types', models.ManyToManyField(related_name='demos', to='webapp.webapptype')),
            ],
            options={
                'verbose_name': 'Web App Demo',
                'verbose_name_plural': 'Web App Demos',
            },
        ),
    ]
