# Generated by Django 5.0.2 on 2025-05-28 14:44

import taggit.managers
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('taggit', '0006_rename_taggeditem_content_type_object_id_taggit_tagg_content_8fc721_idx'),
        ('webapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='webappdemo',
            name='tags',
            field=taggit.managers.TaggableManager(blank=True, help_text='A comma-separated list of tags for this demo', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags'),
        ),
    ]
