# Generated by Django 5.0.2 on 2025-05-28 18:20

import taggit.managers
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taggit', '0006_rename_taggeditem_content_type_object_id_taggit_tagg_content_8fc721_idx'),
        ('webapp', '0002_webappdemo_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='webappdemo',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='webappdemo',
            name='description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='webappdemo',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='webapp_demos/'),
        ),
        migrations.AlterField(
            model_name='webappdemo',
            name='tags',
            field=taggit.managers.TaggableManager(help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags'),
        ),
        migrations.AlterField(
            model_name='webappdemo',
            name='types',
            field=models.ManyToManyField(to='webapp.webapptype'),
        ),
    ]
