# Generated by Django 5.0.2 on 2025-05-28 19:01

import examples.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0003_webappdemo_updated_at_alter_webappdemo_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='webappdemo',
            name='image',
            field=examples.fields.CompressedImageField(blank=True, null=True, upload_to='webapp_demos/'),
        ),
    ]
