# Generated by Django 5.0.2 on 2025-05-29 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0004_alter_webappdemo_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='webappdemo',
            name='types',
            field=models.ManyToManyField(related_name='demos', to='webapp.webapptype'),
        ),
    ]
